### PR TITLE
Make building the project more accessible

### PR DESCRIPTION
**Pull request by pR0Ps**
This PR aims to make building the project easier for users by splitting donation-related functionality (which requires extra configuration files) out into a separate build flavor. It also tweaks the `build.gradle` file to allow debug builds without a keystore present.

See the individual commit messages for more detail.

### CODE REVIEW

**Comment by pR0Ps** [comment]
I'll unmark this as a WIP once I finish rebasing it off the current develop

**Comment by physphil** [comment]
@pR0Ps Cheers mate.  I've created the branch `feature/fdroid` which is based off develop, if you want to target the PR towards that branch that would be great.

**Comment by pR0Ps** [comment]
A couple of notes:
- Gradle:
 - The Gradle stuff is a little janky. I'd like to see it improved but I'm not familiar enough with Gradle to personally make it happen.
 - `google-services` are always added to the classpath (couldn't find a way to only include a classpath for a specific flavor)
 - The `google-services` plugin is always applied if a configuration file for it exists (I took the path for the config file from the `.gitignore`). It's also silently ignored if there's is no configuration file for it. Same as above - couldn't find a way to only apply it for a specific flavor.
- Rationale for which source sets the files were moved into:
 - When a file was only needed for the 'google' build, it was moved to the 'google' source set.
 - When different versions of files were required for different flavors (ex: `menu_conversion_fragment.xml`, `DonateActivity.java`), the different versions were removed from 'main' and put into the 'google' and 'base' source sets.
 - An exception to the above is `AndroidManifest.xml` since the Android Gradle plugin will automatically merge them.
- `ConversionFragment.java` has the option to donate in its menu. This needed to be removed in the 'base' flavor.
 - The 'base' flavor has an empty group (`<group android:id="@+id/menu_donate"/>`) in `menu_conversion_fragment.xml`. This is so the `R.id.menu_donate` constant will still be valid in `ConversionFragment.java` to allow it to compile.
 - The 'base' flavor version of `DonateActivity.java` is just an empty class that defines a `start` function. This is so the line `DonateActivity.start(getActivity());` in `ConversionFragment.java` will compile without errors.

Let me know if you have questions/comments/suggestions!

**Comment by physphil** [comment]
Looks good, thanks again!

**Pull request merged**
